Repository TEAM-README/Readme-AOS, pull requests merged in 2022-05, with the labels that each got.

#19 [fix] Dependencies 오타 고침 (#16)
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: 효림🐇, pullRequest🔥, fix

#18 [chore] text style 추가 (#7)
  shared/src/main/res/values/themes.xml
Labels: 창환🐷, pullRequest🔥, chore

#23 [feat] Nickname / 닉네임 설정 모듈 생성 (#20)
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Constants.kt
  feature/set-nick-name/.gitignore
  feature/set-nick-name/build.gradle.kts
  feature/set-nick-name/consumer-rules.pro
  feature/set-nick-name/proguard-rules.pro
  feature/set-nick-name/src/androidTest/java/com/readme/android/set_nick_name/ExampleInstrumentedTest.kt
  feature/set-nick-name/src/main/AndroidManifest.xml
  feature/set-nick-name/src/test/java/com/readme/android/set_nick_name/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 창환🐷, pullRequest🔥, feat

#22 [chore] leakcanary 안드로이드 12 부터 버전충돌 문제 해결 (#21)
  app/src/main/AndroidManifest.xml
Labels: 창환🐷, pullRequest🔥, chore

#28 [ui] home_fragment / 상단 layout_feed_header 마크업 (#27)
  app/src/main/res/layout/activity_main.xml
  feature/main/src/main/res/layout/fragment_home.xml
  feature/main/src/main/res/layout/layout_feed_header.xml
  feature/main/src/main/res/values/strings.xml
  shared/src/main/res/drawable/ic_category.xml
  shared/src/main/res/values/colors.xml
Labels: 효림🐇, pullRequest🔥, ui

#30 [feat] activity_main / BottomNavigation과 ViewPager 연동 (#29)
  app/src/main/java/com/readme/android/MainActivity.kt
  app/src/main/java/com/readme/android/adapter/MainViewPagerAdapter.kt
  app/src/main/res/menu/menu_main.xml
  shared/src/main/res/values/themes.xml
Labels: 효림🐇, pullRequest🔥, feat

#31 [feat] Mypage_Feed / 화면 전체 어댑터 연동 (#26)
  app/src/main/java/com/readme/android/MainActivity.kt
  app/src/main/java/com/readme/android/di/AppModule.kt
  app/src/main/java/com/readme/android/factory/ReadmeFragmentFactory.kt
  core/build.gradle.kts
  core/src/main/java/com/readme/android/core/base/BindingActivity.kt
  core/src/main/java/com/readme/android/core/base/BindingFragment.kt
  core/src/main/java/com/readme/android/core/ext/ResourceExtension.kt
  core/src/main/java/com/readme/android/core/util/Injector.kt
  core/src/main/java/com/readme/android/core/util/ItemDecorationUtil.kt
  core/src/main/java/com/readme/android/core/util/ItemDiffCallback.kt
  core/src/main/java/com/readme/android/core/util/ResolutionMetrics.kt
  domain/src/main/java/com/readme/android/domain/entity/MyPageUser.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/readme/android/main/ui/adapter/FeedAdapter.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageFragment.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageTopAdapter.kt
  feature/main/src/main/res/layout/fragment_my_page.xml
  feature/main/src/main/res/layout/layout_feed_empty.xml
  feature/main/src/main/res/layout/layout_my_page_top.xml
  shared/src/main/res/values/dimens.xml
  shared/src/main/res/values/strings.xml
Labels: 다빈 😂, pullRequest🔥, feat

#32 [add] NickName / SetNickNameActivity 추가 #25
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/readme/android/core/constant/SetNickNameConstant.kt
  core/src/main/java/com/readme/android/core/ext/ResourceExtension.kt
  core/src/main/java/com/readme/android/core/util/BindingAdapters.kt
  feature/set-nick-name/build.gradle.kts
  feature/set-nick-name/src/main/java/com/readme/android/set_nick_name/SetNickNameActivity.kt
  feature/set-nick-name/src/main/java/com/readme/android/set_nick_name/SetNickNameViewModel.kt
  feature/set-nick-name/src/main/res/layout/activity_set_nick_name.xml
  feature/set-nick-name/src/main/res/values/strings.xml
  shared/src/main/res/drawable/shape_rect_alert_red_border_10.xml
  shared/src/main/res/drawable/shape_rect_gray_1_boder_10.xml
  shared/src/main/res/drawable/shape_rect_gray_1_fill_10.xml
  shared/src/main/res/drawable/shape_rect_main_blue_fill_10.xml
  shared/src/main/res/drawable/shape_rect_main_bule_border_10.xml
  shared/src/main/res/values/strings.xml
Labels: 창환🐷, pullRequest🔥, add

#35 [feat] NickName / SetNickNameActivity edittext 조건별로 분기처리 (#33)
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/readme/android/core/util/BindingAdapters.kt
  feature/set-nick-name/src/main/java/com/readme/android/set_nick_name/SetNickNameActivity.kt
  feature/set-nick-name/src/main/res/layout/activity_set_nick_name.xml
  shared/src/main/res/drawable/shape_rect_alert_red_1_border_10.xml
Labels: 창환🐷, pullRequest🔥, feat

#38 [feat] write_feed / write-feed 모듈생성 (#37)
  app/build.gradle.kts
  feature/write-feed/.gitignore
  feature/write-feed/build.gradle.kts
  feature/write-feed/consumer-rules.pro
  feature/write-feed/proguard-rules.pro
  feature/write-feed/src/androidTest/java/com/readme/android/write_feed/ExampleInstrumentedTest.kt
  feature/write-feed/src/main/AndroidManifest.xml
  feature/write-feed/src/test/java/com/readme/android/write_feed/ExampleUnitTest.kt
  settings.gradle.kts
Labels: 창환🐷, feat

#40 [feat] Splash / 스플래시 화면 만들기 (#34)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/readme/android/MainActivity.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core/build.gradle.kts
  core/src/main/AndroidManifest.xml
  data/build.gradle.kts
  data/src/main/AndroidManifest.xml
  feature/main/build.gradle.kts
  feature/main/src/main/AndroidManifest.xml
  feature/set-nick-name/build.gradle.kts
  feature/set-nick-name/src/main/AndroidManifest.xml
  feature/write-feed/build.gradle.kts
  feature/write-feed/src/main/AndroidManifest.xml
  gradle/wrapper/gradle-wrapper.properties
  shared/build.gradle.kts
  shared/src/main/AndroidManifest.xml
  shared/src/main/res/drawable/ic_logo.xml
  shared/src/main/res/values/themes.xml
Labels: 다빈 😂, pullRequest🔥
