Repository TEAM-README/Readme-AOS, pull requests merged in 2022-04, with the labels that each got.

#4 [chore] 리소스 모듈 파기 (#3)
  .idea/gradle.xml
  app/build.gradle.kts
  feature/home/build.gradle.kts
  settings.gradle.kts
  shared/.gitignore
  shared/build.gradle.kts
  shared/consumer-rules.pro
  shared/proguard-rules.pro
  shared/src/androidTest/java/com/readme/android/shared/ExampleInstrumentedTest.kt
  shared/src/main/AndroidManifest.xml
  shared/src/main/res/values-night/themes.xml
  shared/src/main/res/values/colors.xml
  shared/src/main/res/values/strings.xml
  shared/src/main/res/values/themes.xml
  shared/src/test/java/com/readme/android/shared/ExampleUnitTest.kt
Labels: chore, 다빈 😂

#8 [chore] style guide 지정 (#7)
  .idea/misc.xml
  shared/src/main/res/font/pretendard.xml
  shared/src/main/res/font/pretendard_black.otf
  shared/src/main/res/font/pretendard_bold.otf
  shared/src/main/res/font/pretendard_extra_bold.otf
  shared/src/main/res/font/pretendard_extra_light.otf
  shared/src/main/res/font/pretendard_light.otf
  shared/src/main/res/font/pretendard_medium.otf
  shared/src/main/res/font/pretendard_regular.otf
  shared/src/main/res/font/pretendard_semi_bold.otf
  shared/src/main/res/font/pretendard_thin.otf
  shared/src/main/res/values/colors.xml
Labels: 창환🐷, pullRequest🔥, chore

#10 [ui] MainAvtivity UI작업 (Bottom Navigation, FAB) (#9)
  app/src/main/res/color/selector_bottom_navi.xml
  app/src/main/res/drawable/ic_fab_post.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_my_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_main.xml
  app/src/main/res/values/strings.xml
Labels: 효림🐇, ui

#11 [chore] FIrebase Crashlytics 추가 (#5)
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  buildSrc/src/main/kotlin/Versions.kt
  gradlew
Labels: 다빈 😂

#15 [chore] 상단바 컬러 변경 util 생성 (#14)
  core/src/main/java/com/readme/android/core/util/ActivityExtension.kt
  core/src/main/java/com/readme/android/core/util/ResourceExtension.kt
Labels: 효림🐇, pullRequest🔥, chore
