Repository TEAM-README/Readme-AOS, pull requests merged in 2022-09, with the labels that each got.

#112 [feat] 카카오 로그인 연동 (#109)
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/readme/android/READMEApplication.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  feature/auth/build.gradle.kts
  feature/auth/proguard-rules.pro
  feature/auth/src/main/java/com/readme/android/auth/social_login_manager/KakaoLoginManager.kt
  feature/auth/src/main/java/com/readme/android/auth/social_login_manager/NaverLoginManager.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/LoginActivity.kt
  feature/auth/src/main/res/layout/activity_login.xml
  feature/main/src/main/res/layout/fragment_filter_bottom_sheet.xml
  feature/set-nick-name/src/main/res/layout/activity_set_nick_name.xml
  feature/write-feed/src/main/res/layout/activity_post_feed.xml
  feature/write-feed/src/main/res/layout/activity_register_done.xml
  feature/write-feed/src/main/res/layout/fragment_choose_category.xml
  feature/write-feed/src/main/res/layout/fragment_feeling.xml
  feature/write-feed/src/main/res/layout/fragment_impressive_sentence.xml
  gradle/common.gradle
Labels: 효림🐇, feat

#115 [fix] FeedDetailActivity / BookInfo data class 수정 (#114)
  data/src/main/java/com/readme/android/data/remote/mapper/FeedMapper.kt
  data/src/main/java/com/readme/android/data/remote/mapper/HomeFeedMapper.kt
  data/src/main/java/com/readme/android/data/remote/model/response/Feed.kt
  data/src/main/java/com/readme/android/data/repository/FeedRepositoryImpl.kt
  domain/src/main/java/com/readme/android/domain/entity/BookInfo.kt
  domain/src/main/java/com/readme/android/domain/entity/response/DomainDetailFeedResponse.kt
  feature/main/src/main/java/com/readme/android/main/viewmodel/FeedViewModel.kt
  feature/set-nick-name/src/main/res/layout/activity_set_nick_name.xml
  feature/write-feed/src/main/java/com/readme/android/write_feed/fragments/ImpressiveSentenceFragment.kt
  shared/src/main/res/layout/layout_book_information.xml
Labels: 효림🐇, pullRequest🔥, fix

#118 [fix] 글쓰기 완료후 finish 할시 mainActivity 에서 feed 표시되도록 수정 (#116)
  app/src/main/java/com/readme/android/MainActivity.kt
  app/src/main/java/com/readme/android/navigator/MainNavigatorImpl.kt
  feature/write-feed/src/main/java/com/readme/android/write_feed/postfeed/PostFeedActivity.kt
  navigator/src/main/java/com/readme/android/navigator/Navigator.kt
Labels: 창환🐷, pullRequest🔥, fix

#120 [fix] 한글 두글자 이상 안써지는 부분 해결 (#119)
  feature/set-nick-name/src/main/java/com/readme/android/set_nick_name/SetNickNameActivity.kt
Labels: 창환🐷, pullRequest🔥, fix

#121 [chore] 깃허브 액션에 로컬 프로퍼티 추가
  .github/workflows/pr_builder.yml
Labels: 다빈 😂, chore

#123 [feat] MyPage / 마이페이지 서버연동(#59)
  app/build.gradle.kts
  app/proguard-rules.pro
  app/src/main/java/com/readme/android/di/RemoteDataSourceModule.kt
  app/src/main/java/com/readme/android/di/RepositoryModule.kt
  app/src/main/java/com/readme/android/di/RetrofitServiceModule.kt
  core-data/proguard-rules.pro
  core-data/src/main/java/com/readme/android/core_data/util/CalendarUtil.kt
  core-ui/proguard-rules.pro
  core-ui/src/main/java/com/readme/android/core_ui/base/BindingActivity.kt
  core-ui/src/main/java/com/readme/android/core_ui/util/BindingAdapters.kt
  core-ui/src/main/java/com/readme/android/core_ui/util/UiState.kt
  data/proguard-rules.pro
  data/src/main/java/com/readme/android/data/remote/datasource/RemoteUserDataSource.kt
  data/src/main/java/com/readme/android/data/remote/datasource/RemoteUserDataSourceImpl.kt
  data/src/main/java/com/readme/android/data/remote/mapper/FeedMapper.kt
  data/src/main/java/com/readme/android/data/remote/model/response/MyFeedResponse.kt
  data/src/main/java/com/readme/android/data/remote/service/UserService.kt
  data/src/main/java/com/readme/android/data/repository/FeedRepositoryImpl.kt
  data/src/main/java/com/readme/android/data/repository/UserRepositoryImpl.kt
  domain/build.gradle.kts
  domain/src/main/java/com/readme/android/domain/entity/MyPageInfo.kt
  domain/src/main/java/com/readme/android/domain/entity/MyPageUser.kt
  domain/src/main/java/com/readme/android/domain/repository/UserRepository.kt
  feature/auth/proguard-rules.pro
  feature/book-search/proguard-rules.pro
  feature/main/build.gradle.kts
  feature/main/proguard-rules.pro
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageFragment.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageTopAdapter.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageViewModel.kt
  feature/main/src/main/java/com/readme/android/main/viewmodel/FeedViewModel.kt
  feature/main/src/main/res/layout/activity_feed_detail.xml
  feature/main/src/main/res/layout/fragment_my_page.xml
  feature/main/src/main/res/layout/item_feed.xml
  feature/main/src/main/res/layout/layout_mypage_feed_empty.xml
  feature/set-nick-name/proguard-rules.pro
  feature/write-feed/proguard-rules.pro
  navigator/proguard-rules.pro
  shared/proguard-rules.pro
Labels: 다빈 😂, pullRequest🔥, feat

#127 [feat] Mypage_Settings / 마이페이지_설정 뷰 구현
  core-ui/src/main/java/com/readme/android/core_ui/base/BindingActivity.kt
  core-ui/src/main/java/com/readme/android/core_ui/ext/ContextExtension.kt
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/readme/android/data/remote/service/UserService.kt
  data/src/main/java/com/readme/android/data/repository/UserRepositoryImpl.kt
  domain/src/main/java/com/readme/android/domain/repository/UserRepository.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/LoginActivity.kt
  feature/book-search/src/main/java/com/readme/android/book_search/BookSearchActivity.kt
  feature/main/build.gradle.kts
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageFragment.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageViewModel.kt
  feature/main/src/main/java/com/readme/android/main/view/MoreBottomSheetDialog.kt
  feature/main/src/main/res/layout/activity_my_page_setting.xml
  feature/set-nick-name/src/main/java/com/readme/android/set_nick_name/SetNickNameActivity.kt
  feature/write-feed/src/main/java/com/readme/android/write_feed/postfeed/PostFeedActivity.kt
  feature/write-feed/src/main/java/com/readme/android/write_feed/writefeed/FeedWriteActivity.kt
  shared/src/main/java/com/readme/android/shared/custom/ReadmeDialogFragment.kt
  shared/src/main/res/layout/fragment_readme_dialog.xml
  shared/src/main/res/values/strings.xml
Labels: 다빈 😂, pullRequest🔥, feat

#130 [fix] Mypage / 마이페이지 엠티뷰 수정하기
  feature/main/src/main/res/layout/fragment_my_page.xml
  feature/main/src/main/res/layout/layout_mypage_feed_empty.xml
Labels: 다빈 😂, fix

#133 [feat] 디버그 / 릴리즈 용 BaseURL 구분 및 온보딩 구현 (#132, #41)
  .github/workflows/pr_builder.yml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/readme/android/di/RetrofitModule.kt
  app/src/main/java/com/readme/android/navigator/MainNavigatorImpl.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/Versions.kt
  core-ui/build.gradle.kts
  core-ui/src/main/java/com/readme/android/core_ui/base/BindingFragment.kt
  core-ui/src/main/java/com/readme/android/core_ui/ext/ActivityExtension.kt
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/readme/android/data/repository/LoginRepositoryImpl.kt
  domain/src/main/java/com/readme/android/domain/repository/LoginRepository.kt
  feature/auth/build.gradle.kts
  feature/auth/src/main/java/com/readme/android/auth/ui/AuthActivity.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/LoginFragment.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/LoginViewModel.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/OnBoardFragment.kt
  feature/auth/src/main/java/com/readme/android/auth/ui/adapter/OnBoardAdapter.kt
  feature/auth/src/main/res/drawable-hdpi/img_onboarding_1.webp
  feature/auth/src/main/res/drawable-hdpi/img_onboarding_2.webp
  feature/auth/src/main/res/drawable-hdpi/img_onboarding_3.webp
  feature/auth/src/main/res/drawable-mdpi/img_onboarding_1.webp
  feature/auth/src/main/res/drawable-mdpi/img_onboarding_2.webp
  feature/auth/src/main/res/drawable-mdpi/img_onboarding_3.webp
  feature/auth/src/main/res/drawable-xhdpi/img_onboarding_1.webp
  feature/auth/src/main/res/drawable-xhdpi/img_onboarding_2.webp
  feature/auth/src/main/res/drawable-xhdpi/img_onboarding_3.webp
  feature/auth/src/main/res/drawable-xxhdpi/img_onboarding_1.webp
  feature/auth/src/main/res/drawable-xxhdpi/img_onboarding_2.webp
  feature/auth/src/main/res/drawable-xxhdpi/img_onboarding_3.webp
  feature/auth/src/main/res/drawable-xxxhdpi/img_onboarding_1.webp
  feature/auth/src/main/res/drawable-xxxhdpi/img_onboarding_2.webp
  feature/auth/src/main/res/drawable-xxxhdpi/img_onboarding_3.webp
  feature/auth/src/main/res/layout/activity_auth.xml
  feature/auth/src/main/res/layout/fragment_login.xml
  feature/auth/src/main/res/layout/fragment_on_board.xml
  feature/auth/src/main/res/layout/layout_onboard_1.xml
  feature/auth/src/main/res/layout/layout_onboard_2.xml
  feature/auth/src/main/res/layout/layout_onboard_3.xml
  feature/auth/src/main/res/layout/layout_onboard_holder.xml
  shared/src/main/res/values/strings.xml
  shared/src/main/res/values/themes.xml
Labels: 다빈 😂, pullRequest🔥, feat

#135 [fix] 로그아웃 시 온보딩으로 가는 에러 해결 (#134)
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSource.kt
  data/src/main/java/com/readme/android/data/local/datasource/LocalPreferenceUserDataSourceImpl.kt
  data/src/main/java/com/readme/android/data/repository/UserRepositoryImpl.kt
Labels: 다빈 😂, pullRequest🔥, fix

#136 [chore] Release 브랜치에서 versionCode, versionName변경
  buildSrc/src/main/kotlin/Constants.kt
  gradle/common.gradle
Labels: 효림🐇, chore

#138 [chore] mypage_setting / 이용약관 -> 개인정보처리방침으로 링크 변경 (#137)
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
Labels: 다빈 😂, pullRequest🔥, chore

#139 [chore] mypage_setting / 이용약관 -> 개인정보처리방침으로 링크 변경 (#137)
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
Labels: 다빈 😂, chore

#140 [chore] 개인정보처리방침 링크 및 버전 수정 (#137)
  buildSrc/src/main/kotlin/Constants.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
Labels: 다빈 😂, 효림🐇, pullRequest🔥, chore

#143 [chore] activity_my_page_setting / 약관 보기 -> 개인정보처리방침 (#142)
  buildSrc/src/main/kotlin/Constants.kt
  feature/main/src/main/res/layout/activity_my_page_setting.xml
  shared/src/main/res/values/strings.xml
Labels: 효림🐇, pullRequest🔥, hotfix

#145 [hotfix] 환경설정 / 개인정보처리방침 url 변경 (#144)
  buildSrc/src/main/kotlin/Constants.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
Labels: 효림🐇, pullRequest🔥, hotfix

#146 Master
  buildSrc/src/main/kotlin/Constants.kt
  feature/main/src/main/java/com/readme/android/main/ui/mypage/MyPageSettingActivity.kt
  feature/main/src/main/res/layout/activity_my_page_setting.xml
  shared/src/main/res/values/strings.xml
Labels: 효림🐇, pullRequest🔥, hotfix
